lista = []
numero = int(input("Ingrese el primer numero: ", ))
numero_2 = int(input("Ingrese el segundo numero: ", ))
numero_3 = int(input("Ingrese el tercer numero: ", ))
numero_4 = int(input("Ingrese el cuarto numero: ", ))
lista.append(numero)
lista.append(numero_2)
lista.append(numero_3)
lista.append(numero_4)
lista.sort()
print(lista)